import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:paycron_app/src/domain/usecase/complete_profile_usecase.dart';
import 'package:paycron_app/src/domain/usecase/get_profile_usecase.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:paycron_app/src/presentation/router/app_router.dart';
import 'package:paycron_app/src/core/services/network/api_client.dart';
import 'package:paycron_app/src/core/services/network/api_service.dart';
import 'package:paycron_app/src/core/services/network/i_api_service.dart';
import 'package:paycron_app/src/core/services/snackbar/i_snackbar_service.dart';
import 'package:paycron_app/src/core/services/snackbar/snackbar_service.dart';
import 'package:paycron_app/src/core/services/storage/i_local_storage_service.dart';
import 'package:paycron_app/src/core/services/storage/local_storage_service.dart';
import 'package:paycron_app/src/core/utils/api_end_points.dart';
import 'package:paycron_app/src/data/repositories/auth_repository.dart';
import 'package:paycron_app/src/data/repositories/home_repository.dart';
import 'package:paycron_app/src/domain/repositories/i_home_repositoty.dart';
import 'package:paycron_app/src/domain/usecase/home_usecase.dart';
import 'package:paycron_app/src/domain/usecase/signin_usecase.dart';
import 'package:paycron_app/src/domain/usecase/signup_usecase.dart';
import 'package:paycron_app/src/data/repositories/profile_repository.dart';

import 'package:paycron_app/src/domain/repositories/i_profile_repositoty.dart';
import 'package:paycron_app/src/domain/repositories/i_auth_repository.dart';
import 'package:paycron_app/src/domain/usecase/email_verified_usecase.dart';

part 'dependency_injection.g.dart';
part 'parts/services.dart';
part 'parts/repository.dart';
part 'parts/usecase.dart';
