name: Flutter - Android Build APK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # 🔐 Decode keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      # 🔐 Decode key.properties
      - name: Decode key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties

      # 🧱 Build APK (NO flavor)
      - name: Build APK
        run: flutter build apk --release

      # 📦 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk